### ISSUE TITLE
Consideration about Sign Language translation to text or other by motion detectiong and Ocr reading

### ISSUE THREAD

**Issue by Leekeunyoung** [MicrosoftDocs/azure-docs.ko-kr#1019]
[여기에 피드백 입력]
I am now uploading Korea Sign Language clip video with subtitle manifesting the meaning of the signlang motion into text, hoping the processed through VideoIndexer.ai catch both motion and ocr.
If simultaneous catching is possibe(though by my project editing or whatever) I think that can make it possible for Sign Lang translate video machine or device just like SignAll's video A.I. to enlighten and broaden the communication between SL-blind person with the Deaf person.
Nevertheless they(Sign All) only treat American Sign Language. So I felt urged to follow their performance in Korean Sign Language's area(translate SL->TEXT or anything else)
How can I get help from Azure Video Analytics? Seriously from Republic Of Korea. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: eee5b69c-0b80-2537-b366-cf00642ba321
* Version Independent ID: 5f6bce6e-0ced-9ac4-4035-2d13d952aa00
* Content: [Azure 미디어 분석으로 동작 검색](https://docs.microsoft.com/ko-kr/azure/media-services/previous/media-services-motion-detection)
* Content Source: [articles/media-services/previous/media-services-motion-detection.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/media-services/previous/media-services-motion-detection.md)
* Service: **media-services**
* GitHub Login: @Juliako
* Microsoft Alias: **juliako**

**Comment by srvbpigh** [comment]
Hello, @Leekeunyoung
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Leekeunyoung** [comment]
Thanks for your feedback!! 

Good day^-^" 

From Republic Of Korea


Lee keun young 

On 2019-09-22 13:58, srvbpigh wrote: 

> Hello,
@Leekeunyoung [1] 
> 
> Thank you for your feedback. 
> 
> We are
actively reviewing your comments and will get back to you soon. 
> 
>
Kind regards,
> Microsoft DOCS International Team 
> 
> --
> You are
receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [2], or mute the thread [3].



Links:
------
[1] https://github.com/Leekeunyoung
[2]
https://github.com/MicrosoftDocs/azure-docs.ko-kr/issues/1019?email_source=notifications&amp;email_token=ALBG24UCCD24RREWERDOHCLQK3YK3A5CNFSM4IZBF45KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7I6INA#issuecomment-533849140
[3]

**Comment by CeciAc** [comment]
Hello, @Leekeunyoung

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
