### ISSUE TITLE
한글 번역 오타(Microsft) 수정 요청 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1049]
"인사이트정보" 섹션의 컨테이너용 Azure Monitor(Azure Monitor for containers)가 Microsft로 잘못 표기되어 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 144afccf-4ab9-bb34-957d-e86d3732d688
* Version Independent ID: 863b80ff-f60a-e727-dc12-0d6aba937df6
* Content: [Azure Monitor 개요](https://docs.microsoft.com/ko-kr/azure/azure-monitor/overview#feedback)
* Content Source: [articles/azure-monitor/overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/azure-monitor/overview.md)
* Service: **azure-monitor**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @zer0big  님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/azure-monitor/overview#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
