### ISSUE TITLE
Wrong translation in Korean doc

### ISSUE THREAD

**Issue by pskalyber** [MicrosoftDocs/azure-docs.ko-kr#1051]
see https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/text-to-speech#sdk-quickstarts

For the platform of python SDK, "창" should be "Windows"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e873515a-55f7-ecdf-37dd-9b5dbb13c211
* Version Independent ID: f8b9132b-c867-cd3a-c772-eaa87108711b
* Content: [텍스트 음성 변환-음성 서비스 - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/text-to-speech)
* Content Source: [articles/cognitive-services/Speech-Service/text-to-speech.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/cognitive-services/Speech-Service/text-to-speech.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @pskalyber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pskalyber
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/text-to-speech

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
