### ISSUE TITLE
Wrong translation in Korean doc

### ISSUE THREAD

**Issue by pskalyber** [MicrosoftDocs/azure-docs.ko-kr#1052]
see https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/rest-text-to-speech

"끝점" should be translated to "엔드포인트" for consistency.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e351e013-771a-bfdc-0f76-815316c7717d
* Version Independent ID: 8c3a1bbe-196a-13b8-f905-b8ea7bfd0e7a
* Content: [텍스트 음성 변환 API 참조 (REST)-음성 서비스 - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/rest-text-to-speech#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/rest-text-to-speech.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/cognitive-services/Speech-Service/rest-text-to-speech.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by pskalyber** [comment]
There are a few more "끝점"s on the page.

**Comment by srvbpigh** [comment]
Hello, @pskalyber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @pskalyber 
Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/rest-text-to-speech du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by pskalyber** [comment]
Thank you @CeciAc 

Unfortunately, I found that there are still "끝점," which is a wrongly translated word on the https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/rest-text-to-speech. Those should be fixed to "엔드포인트."
