### ISSUE TITLE
리소스 관리자 템플릿을 선택 해야 하는 이유 섹션 오타 수정

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1056]
[여기에 피드백 입력]
"코드를 코드로: Azure Policy 는 거 버 넌 스를 자동화 하는 코드 프레임 워크로 서의 정책입니다."
행에서 원문이 Policy as code이므로 "코드로서의 정책"이 올바른 표현이 될 것 같습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e322a1e2-ce06-95e4-81ba-e61571064ad6
* Version Independent ID: 04b6f3ae-deae-a666-7eec-f17644423c8d
* Content: [Azure Resource Manager 템플릿 개요](https://docs.microsoft.com/ko-kr/azure/azure-resource-manager/template-deployment-overview?source=docs)
* Content Source: [articles/azure-resource-manager/template-deployment-overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/azure-resource-manager/template-deployment-overview.md)
* Service: **azure-resource-manager**
* GitHub Login: @tfitzmac
* Microsoft Alias: **tomfitz**

**Comment by zer0big** [comment]
![image](https://user-images.githubusercontent.com/38598117/69051357-69128a80-0a47-11ea-9c92-90d0ef97221a.png)

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
안녕하세요, @zer0big 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/azure-resource-manager/template-deployment-overview?source=docs 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
