### ISSUE TITLE
본문 오타 수정

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1057]
[여기에 피드백 입력]
소스 제거 --> 소스 제어

자격 증명이 개발자 워크스테이션에 표시되지 않고 **소스 제거**에 체크 인되지 않는 것이 가장 좋습니다.
--> 자격 증명이 개발자 워크스테이션에 표시되지 않고 **소스 제어**에 체크 인 되지 않는 것이 가장 좋습니다. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 72861cc1-7081-cf6e-b7f9-e700a16faa9a
* Version Independent ID: c870872d-0559-6b77-280f-f478e8c84776
* Content: [Azure 리소스에 대한 관리 ID](https://docs.microsoft.com/ko-kr/azure/active-directory/managed-identities-azure-resources/overview)
* Content Source: [articles/active-directory/managed-identities-azure-resources/overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/active-directory/managed-identities-azure-resources/overview.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @zer0big님.
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/active-directory/managed-identities-azure-resources/overview 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
