### ISSUE TITLE
띄어쓰기 고쳐주세요

### ISSUE THREAD

**Issue by gyh0111** [MicrosoftDocs/azure-docs.ko-kr#1059]
지원 되는 원본/싱크 매트릭스 를 사용 하 여 복사 작업
===&gt;
지원 되는 원본/싱크 매트릭스를 사용 하여 복사 작업

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ec2f6a95-1e1e-408a-1afa-b67a68044f52
* Version Independent ID: d2be3a4a-e45d-221b-c63f-f6f6f81565e9
* Content: [Azure Data Factory를 사용하여 Salesforce Marketing Cloud에서 데이터 복사](https://docs.microsoft.com/ko-kr/azure/data-factory/connector-salesforce-marketing-cloud#feedback)
* Content Source: [articles/data-factory/connector-salesforce-marketing-cloud.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/data-factory/connector-salesforce-marketing-cloud.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by srvbpigh** [comment]
Hello, @gyh0111
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @gyh0111 님.
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/data-factory/connector-salesforce-marketing-cloud#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
