### ISSUE TITLE
main.tf 문법오류

### ISSUE THREAD

**Issue by Sanses** [MicrosoftDocs/azure-docs.ko-kr#1061]
tags {
   environment = "staging"
 }

==&gt;
아래와 같이 변경해야 합니다.
 tags = {
   environment = "staging"
 }

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: d6a7a232-6e5d-ae1d-3b57-71fb75740fb4
* Version Independent ID: 1573ac54-ab15-2649-cccd-2dd64c640fc1
* Content: [자습서 - Terraform 및 HCL로 Azure VM 클러스터 만들기](https://docs.microsoft.com/ko-kr/azure/terraform/terraform-create-vm-cluster-with-infrastructure#feedback)
* Content Source: [articles/terraform/terraform-create-vm-cluster-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/terraform/terraform-create-vm-cluster-with-infrastructure.md)

**Comment by srvbpigh** [comment]
Hello, @Sanses
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @Sanses님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/45576에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
