### ISSUE TITLE
Deployment options --> Deployment Center 업데이트 필요

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1063]
"GitHub에서 배포 슬롯으로 배포" 섹션의 Deployment options에 의한 배포과정은 더 이상 유효하지 않습니다.
Deployment Center를 통한 배포 내용으로 업데이트가 필요합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0b20bce3-61cd-4fe8-78b8-d9d9cf263662
* Version Independent ID: 133f48aa-15b6-bcc1-6b4f-067871772a09
* Content: [자습서 - Terraform을 사용하여 Azure 배포 슬롯으로 인프라 프로비전](https://docs.microsoft.com/ko-kr/azure/terraform/terraform-slot-walkthru)
* Content Source: [articles/terraform/terraform-slot-walkthru.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/terraform/terraform-slot-walkthru.md)

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/46063에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
