### ISSUE TITLE
Please update in Azure Pricing page/Azure Portal/translation

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/azure-docs.ko-kr#1064]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/azure-docs/issues/46209

I disregarded the comments not related to localization.

@bibury commented 3 hours ago — with docs.microsoft.com
With regards to "If you migrate your storage account from RA-GRS to GRS or LRS, that account is billed as RA-GRS for an additional 30 days beyond the date that it was converted."

[...]
Also, translation from English to Korea is not correct.
    URL: https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy#are-there-any-costs-to-changing-my-accounts-replication-strategy

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e97d5014-156b-2eed-3c1f-2c29cdb725e3
* Version Independent ID: d6350a48-4ff9-7a63-568c-c4155d1ec89e
* Content: [Azure Storage에서 데이터 중복성](https://docs.microsoft.com/ko-kr/azure/storage/common/storage-redundancy#are-there-any-costs-to-changing-my-accounts-replication-strategy)
* Content Source: [articles/storage/common/storage-redundancy.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/storage/common/storage-redundancy.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @bibury 
	
Thank you for your contribution.
	
Contributions on translation problems against machine translated content are currently not accepted.
	
We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.
	
Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.
	
Many thanks for your support.
	
Microsoft DOCS Global Experience Team
