### ISSUE TITLE
섹션 제목 수정 - Kubernetes 클러스터를 만듭니다. 

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1065]
섹션 제목이 문어체로 되어 있습니다. 
"Kubernetes 클러스터를 만듭니다."를 "Kubernetes 클러스터 만들기"로 변경하면 좋을 듯 합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: c22b6ec6-7a27-4029-ff8f-674a40c0e552
* Version Independent ID: bd2884f3-831a-3761-0502-5eb1594872bd
* Content: [자습서 - Terraform을 사용하여 AKS(Azure Kubernetes Service)로 Kubernetes 클러스터 만들기](https://docs.microsoft.com/ko-kr/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md)

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요, @zer0big.   

 피드백을 주셔서 감사합니다.  

 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks 에 게시했습니다.   

 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

 감사합니다.  

Microsoft DOCS 국제 팀
