### ISSUE TITLE
번역 오류 정정 요청

### ISSUE THREAD

**Issue by lormadus** [MicrosoftDocs/azure-docs.ko-kr#1066]
[As-Is]
이미지 정의에서 VM을 배포 하는 것이 아니라 정의에서 만든 이미지 버전에서 VM을 배포 하지 않습니다.
[To-Be]
이미지 정의에서 VM을 배포 하는 것이 아니라 정의에서 만든 이미지 버전에서 VM을 배포합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0d150ace-bd6d-8111-79b5-0ce7cb76a378
* Version Independent ID: 13a828ae-ae92-9ea7-5f37-5a69eeeb87b7
* Content: [Azure 공유 이미지 갤러리](https://docs.microsoft.com/ko-kr/azure/virtual-machines/windows/shared-image-galleries#feedback)
* Content Source: [articles/virtual-machines/windows/shared-image-galleries.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/virtual-machines/windows/shared-image-galleries.md)
* Service: **virtual-machines-windows**
* GitHub Login: @axayjo
* Microsoft Alias: **akjosh**

**Comment by srvbpigh** [comment]
Hello, @lormadus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요 @lormadus 님, 

기여해 주셔서 감사합니다. 

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
