### ISSUE TITLE
오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by Ko-JoonYoung** [MicrosoftDocs/azure-docs.ko-kr#1067]
Repository를 Registry로 잘못 표기된 것은 아닌지요.
Sample Project 이름에 'Edge'라는 단어가 'Ege'로 표기 되어있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8b7b666c-1e95-d0dd-7fd8-a2367369d190
* Version Independent ID: 3eff6d45-cf8b-4546-166d-16198c736f13
* Content: [Visual Studio에서 모듈 개발 및 디버그-Azure IoT Edge](https://docs.microsoft.com/ko-kr/azure/iot-edge/how-to-visual-studio-develop-module#feedback)
* Content Source: [articles/iot-edge/how-to-visual-studio-develop-module.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/iot-edge/how-to-visual-studio-develop-module.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by srvbpigh** [comment]
Hello, @Ko-JoonYoung
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요 @Ko-JoonYoung  님, 

기여해 주셔서 감사합니다. 
 
기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
