### ISSUE TITLE
"AKS 클러스터에 대한 서비스 주체 지정" 섹션 내 번역 오류 정정 제안 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1068]
해당 섹션 내 후반 부에 "password 합니다."라는 오류가 있습니다. 다음과 같이 수정 제안 드립니다.

- 기존 문장
"Az AKS create 명령을 사용 하 여 AKS 클러스터를 만들 때 기존 서비스 주체를 사용 하려면 --service-principal 및 --client-secret 매개 변수를 사용 하 여 az ad sp create-rbac 명령의 출력에서 appId을 지정 하 고 password 합니다."

- 제안 문장
"az aks create 명령을 사용하여 AKS 클러스터를 생성할 때 기존 서비스 주체를 사용하려면 --service-principal 및 --client-secret 매개 변수를 사용하여 az ad sp create-rbac 명령의 출력에서 appId와 password를 지정합니다."

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 25a0d502-ce71-76d4-bf8a-060e63913b52
* Version Independent ID: 69d7fa26-1a37-e477-0a2c-db58ce19a84f
* Content: [AKS(Azure Kubernetes Service)에 대한 서비스 주체](https://docs.microsoft.com/ko-kr/azure/aks/kubernetes-service-principal)
* Content Source: [articles/aks/kubernetes-service-principal.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/kubernetes-service-principal.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by zer0big** [comment]
"az aks create 명령을 사용하여 AKS 클러스터를 생성할 때 기존 서비스 주체를 사용하려면 --service-principal 및 --client-secret 매개 변수를 사용하여 az ad sp create-rbac 명령의 출력에서 appId와 password를 지정합니다." 로 정정 제안 드립니다.

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요 @zer0big 님, 

기여해 주셔서 감사합니다. 

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
