### ISSUE TITLE
수신 컨트롤러 Helm 차트 설치 섹션 내 오류 내용 수정 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1072]
실습결과에 502 코드가 유발되어 디버깅 하던 도중 확인된 오류 내용 공유 및 정정 검토 요청 드립니다.

수신 컨트롤러 Helm 차트 설치 섹션 내 주요 참고 사항 내용 중 "identityResourceID 값"과 "identityClientID 값"의 확인 방법이 반대로 안되어 있습니다.
값을 반대로 입력하였기 때문에 502에러가 유발된 것입니다. 
다음과 같이 정정 요청 드립니다.

- 변경 전
주요 참고 사항:
identityResourceID 값은 terraform 스크립트에서 생성되고 echo "$(terraform output identity_client_id)"를 실행하여 찾을 수 있습니다.
identityClientID 값은 terraform 스크립트에서 생성되고 echo "$(terraform output identity_resource_id)"를 실행하여 찾을 수 있습니다.

- 변경 후
주요 참고 사항:
identityResourceID 값은 terraform 스크립트에서 생성되고 echo "$(terraform output identity_resource_id)"를 실행하여 찾을 수 있습니다.
identityClientID 값은 terraform 스크립트에서 생성되고 echo "$(terraform output identity_client_id)"를 실행하여 찾을 수 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 20f12c89-40e2-076e-6135-64773551e673
* Version Independent ID: c2d6ac4a-fad9-dbc1-d125-b267bcd2a566
* Content: [자습서 - Azure Kubernetes Service에 Application Gateway 수신 컨트롤러 만들기](https://docs.microsoft.com/ko-kr/azure/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress.md)

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46907](https://github.com/MicrosoftDocs/azure-docs/issues/46907) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/46907에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
