### ISSUE TITLE
파일 패스 정보 오류 정정 

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1073]
다음 2개의 파일 패스 정보 오류가 발견되어 정정 검토 요청 드립니다.

인터넷의 애플리케이션 액세스 섹션
charts/example-java/values.yaml --&gt; charts/java/values.yaml

애플리케이션 반복 섹션
Src/main/java/helloworld/Hello --&gt; src/main/java/helloworld/Hello.java

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0b3d2f14-f40d-1f84-0506-c87d7f8db59b
* Version Independent ID: a16becae-3e1f-78ed-0031-758f331e7021
* Content: [Draft를 사용 하 여 AKS (Azure Kubernetes Service)에서 개발](https://docs.microsoft.com/ko-kr/azure/aks/kubernetes-draft)
* Content Source: [articles/aks/kubernetes-draft.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/kubernetes-draft.md)
* Service: **container-service**
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46976](https://github.com/MicrosoftDocs/azure-docs/issues/46976) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/46976에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
