### ISSUE TITLE
유휴 시간 후 첫번쨰 요청에 대한 응답시간 줄이기 에 대한설명에 대해 메뉴얼과 실제 포탈이 차이가있습니다.

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#1074]
해당 메뉴얼엔 아래와 같이 설명되어있습니다.
무중단 설정을 변경하려면:
Azure Portal에서 웹앱으로 이동합니다.
애플리케이션 설정을 선택합니다.
무중단에 대해 켜기를 선택합니다.

하지만 실제 에저포탈에서 웹앱으로 들어간뒤 애플리케이션 설정이라는 항목이없습니다. 
혹시 이 설명이 웹앱 -&gt; 구성 -&gt; 일반설정 -&gt; 항상 사용함 설정 On 이걸 의미하는 걸까요??

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 3e26e5a4-7b72-ba7e-cfed-e31a4a8aaef9
* Version Independent ID: dc783fe3-bd1a-c25e-2b92-903595c0822e
* Content: [응용 프로그램 성능 Faq](https://docs.microsoft.com/ko-kr/azure/app-service/faq-availability-performance-application-issues#feedback)
* Content Source: [articles/app-service/faq-availability-performance-application-issues.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/app-service/faq-availability-performance-application-issues.md)
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by srvbpigh** [comment]
Hello, @yourera
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요 @yourera 님, 

기여해 주셔서 감사합니다. 

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
