### ISSUE TITLE
UDR에 대한 Azure의 최대 경로 지원 갯수 표기 오류 확인 요청(300 --> 400)

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1075]
"고유한 서브넷을 사용한 Kubenet 네트워킹 개요 섹션" 내 UDR 초대 경로 갯수가 300으로 되어 있는데, 영어 원본에는 400으로 되어 있습니다. 확인 및 정정이 필요합니다.
- 자동 번역본
Azure는 UDR에서 최대 300개의 경로를 지원하므로 400개 노드보다 큰 AKS 클러스터를 사용할 수 없습니다.
- 영어 원본
 Azure supports a maximum of 400 routes in a UDR, so you can't have an AKS cluster larger than 400 nodes.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 719f4010-810f-b3c7-d807-222b39b20e20
* Version Independent ID: 82ac8cfa-b0a2-c77a-408a-ab9aa2b6bce4
* Content: [AKS(Azure Kubernetes Service)에서 kubenet 네트워킹 구성](https://docs.microsoft.com/ko-kr/azure/aks/configure-kubenet)
* Content Source: [articles/aks/configure-kubenet.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/configure-kubenet.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
안녕하세요 @zer0big 님, 

기여해 주셔서 감사합니다. 

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다. 

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다. 

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다. 

도움 주셔서 감사합니다. 

Microsoft DOCS Global Experience Team 드림
