### ISSUE TITLE
애플리케이션 배포 관련 문의 : istio/step-1-create-voting-app-gateway.yaml 

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1076]
kubectl apply -f istio/step-1-create-voting-app-gateway.yaml --namespace voting 명령을 수행하면 다음과 같이 "VirtualService", "Gateway" 인식 오류가 발생합니다. 어떻게 해야 하나요?

zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200209 - AKS/aks-voting-app/scenarios/intelligent-routing-with-istio$ kubectl apply -f istio/step-1-create-voting-app-gateway.yaml --namespace 
voting
unable to recognize "istio/step-1-create-voting-app-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio/step-1-create-voting-app-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 04e91998-d53d-5074-5c67-0f9f031bc26c
* Version Independent ID: 989fa4fe-e7a8-2003-6a89-73beaade1b80
* Content: [Azure Kubernetes Service(AKS)에서 Istio를 사용하여 인텔리전트 라우팅 및 카나리아 릴리스](https://docs.microsoft.com/ko-kr/azure/aks/servicemesh-istio-scenario-routing?pivots=client-operating-system-linux)
* Content Source: [articles/aks/servicemesh-istio-scenario-routing.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/servicemesh-istio-scenario-routing.md)
* Service: **container-service**
* GitHub Login: @paulbouwer
* Microsoft Alias: **pabouwer**

**Comment by zer0big** [comment]
istioctl version 이슈로 확인되어 Close 하도록 하겠습니다.
1.3.2에서 해당 명령에 문제 없음을 확인했습니다.

**Comment by zer0big** [comment]
죄송합니다. 제가 다른 명령어와 착각했습니다. 1.3.2에서 여전히 동일한 문제가 발생하고 있습니다.

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @zer0big  님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀
