### ISSUE TITLE
애플리케이션 배포 관련 문의 : istio/step-1-create-voting-app-gateway.yaml

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1079]
kubectl apply -f istio/step-1-create-voting-app-gateway.yaml --namespace voting 명령을 수행하면 다음과 같이 "VirtualService", "Gateway" 인식 오류가 발생합니다. 어떻게 해야 하나요?

zerobig@ZEROBIG-NT800:/mnt/d/Azure-Study/20200209 - AKS/aks-voting-app/scenarios/intelligent-routing-with-istio$ kubectl apply -f istio/step-1-create-voting-app-gateway.yaml --namespace
voting
unable to recognize "istio/step-1-create-voting-app-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio/step-1-create-voting-app-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 04e91998-d53d-5074-5c67-0f9f031bc26c
* Version Independent ID: 989fa4fe-e7a8-2003-6a89-73beaade1b80
* Content: [Azure Kubernetes Service(AKS)에서 Istio를 사용하여 인텔리전트 라우팅 및 카나리아 릴리스](https://docs.microsoft.com/ko-kr/azure/aks/servicemesh-istio-scenario-routing?pivots=client-operating-system-linux#feedback)
* Content Source: [articles/aks/servicemesh-istio-scenario-routing.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/servicemesh-istio-scenario-routing.md)
* Service: **container-service**
* GitHub Login: @paulbouwer
* Microsoft Alias: **pabouwer**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @zer0big  님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀에서 귀하의 피드백을 검토한 결과 이 문제는 이미 기록된 것으로 나타났습니다. 
 문제  https://github.com/MicrosoftDocs/azure-docs.ko-kr/issues/1076 를 확인하세요. 이 문제는 중복되기 때문에 종료하겠습니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
