### ISSUE TITLE
코드 누락 문의

### ISSUE THREAD

**Issue by HyeokIn** [MicrosoftDocs/azure-docs.ko-kr#1080]
[!code-csharp]으로 코드가 보이지 않는 경우에는 어떻게 해야 할까요..?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e4b55e56-55a1-d635-6bea-271dc361d676
* Version Independent ID: 8e9cb28f-c133-f310-3c7d-3a3b7e85f69d
* Content: [빠른 시작: 마이크에서 음성 인식 - Speech Service - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-csharp#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by srvbpigh** [comment]
Hello, @HyeokIn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48072](https://github.com/MicrosoftDocs/azure-docs/issues/48072) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @HyeokIn님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/48072에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
