### ISSUE TITLE
전체 범위 정책이어도 정의되지 않은 API에 대해서는 동작하지 않음

### ISSUE THREAD

**Issue by lesmin-sk** [MicrosoftDocs/azure-docs.ko-kr#1082]
전체 범위 정책으로, <ip-filter> 정책을 정의하면,
허용되지 않은 IP주소 대역에서 API 접근 시 403 Forbidden 에러가 반환됩니다.

하지만, 정의되지 않은 API에 대해서, 허용되지 않은 IP주소 대역에서 접근 시,
403 Forbidden 대신 404 Not Found 에러가 반환됩니다.

기대되는 동작은, ip-filter가 전역 정책이므로 403 Forbidden을 반환해주었으면 하는데,
본 문서에서는 이러한 경우에 대한 설명이 부족합니다.

혹은 <on-error> 정책 내에 다시 <ip-filter> 정책을 추가할 수 있으면,
상기 기대하는 동작 처리가 가능할 것 같으나, 현재 지원되지 않는 것으로 보입니다.

이에 대한 설명도 추가되었으면 합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 250924d9-418b-9a24-90fe-5b3835c3b2a7
* Version Independent ID: cfd91d85-ffff-d2b0-fc7f-61bcae6ed615
* Content: [Azure API Management의 정책](https://docs.microsoft.com/ko-kr/azure/api-management/api-management-howto-policies#scopes)
* Content Source: [articles/api-management/api-management-howto-policies.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/api-management/api-management-howto-policies.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @lesmin-sk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48799](https://github.com/MicrosoftDocs/azure-docs/issues/48799) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @lesmin-sk님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/48799에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
