### ISSUE TITLE
jumpbox ssh 키 생성 누락 및 진행 과정 순서 오류 검토 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1083]
실습을 진행하는 과정에서 jumpbox의 ssh-keygen 내용이 누락되었으며 작업 순서가 뒤바뀐 것을 확인했습니다.

1. 우선  jumpbox를 배포한 뒤 jumpbox에 ssh 접속 후 ssh-keygen을 해주고 그 결과를 vmss 추가 배포 시점에 반영해줘야 하는데 이 부분이 누락 되었습니다.
2. 위 작업이 이루어지고 나서 vmss(가상 머신 확장 집합) 추가 시 ssh key 생성 위치에 대한 정보("key_data = file("~/.ssh/id_rsa.pub")") 가 잘못되어 있는 것으로 보여집니다.

검토 부탁 드립니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 53c1a5f9-06b8-9493-ed1e-df023b8b0e81
* Version Independent ID: 846f170a-0162-6613-f85a-790e210f24d7
* Content: [자습서 - Terraform을 사용하여 Packer 사용자 지정 이미지에서 Azure 가상 머신 확장 집합 만들기](https://docs.microsoft.com/ko-kr/azure/terraform/terraform-create-vm-scaleset-network-disks-using-packer-hcl)
* Content Source: [articles/terraform/terraform-create-vm-scaleset-network-disks-using-packer-hcl.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/terraform/terraform-create-vm-scaleset-network-disks-using-packer-hcl.md)

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48803](https://github.com/MicrosoftDocs/azure-docs/issues/48803) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/48803에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
