### ISSUE TITLE
원문과 다른 뜻으로 번역된 문장 수정 검토 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1084]
**토픽** 섹션에서 다음 원문의 주어는 "subscriber"이고 본동사는 "can receive" 이므로 구독자가 수신할 수 있다는 내용으로 해석되어야 할 듯 합니다. 검토 부탁 드립니다.

원문 : A subscriber to a topic can receive a copy of each message sent to that topic. 

번역문 : 토픽에 대한 구독자는 각 메시지의 복사본을 해당 토픽에 전송할 수 있습니다.

수정 제안문 : 토픽에 대한 구독자는 해당 토픽으로 전송된 각 메시지의 복사본을 수신할 수 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0c3af764-3978-6abe-f756-2c2c4ef47e31
* Version Independent ID: c4dca68a-1c95-42af-9eb3-e1dc9a66a692
* Content: [Azure Service Bus 메시지 개요](https://docs.microsoft.com/ko-kr/azure/service-bus-messaging/service-bus-messaging-overview?source=docs)
* Content Source: [articles/service-bus-messaging/service-bus-messaging-overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/service-bus-messaging/service-bus-messaging-overview.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/service-bus-messaging/service-bus-messaging-overview?source=docs에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀
