### ISSUE TITLE
용어 일관성 유지 관련 

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1085]
이벤트와 메시지 서비스 비교 섹션의 첫 번째 등장하는 "행사"라는 용어는 일관성을 유지하는 차원에서라도 "이벤트"로 표기하는 것이 타당해 보입니다. 검토 부탁 드립니다. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 08e12671-466a-8807-63bb-fb1923554d60
* Version Independent ID: 88dcdcb5-e611-134d-5c2e-66c657416445
* Content: [Azure 메시지 서비스 비교](https://docs.microsoft.com/ko-kr/azure/event-grid/compare-messaging-services?toc=https%3A%2F%2Fdocs.microsoft.com%2Fko-kr%2Fazure%2Fservice-bus-messaging%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fko-kr%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [articles/event-grid/compare-messaging-services.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/event-grid/compare-messaging-services.md)
* Service: **event-grid**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/event-grid/compare-messaging-services?toc=https%3A%2F%2Fdocs.microsoft.com%2Fko-kr%2Fazure%2Fservice-bus-messaging%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fko-kr%2Fazure%2Fbread%2Ftoc.json에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀
