### ISSUE TITLE
Azure CLI 명령 표기 오류 수정 검토 건

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#1086]
배포 실행 명령 섹션의 Azure CLI 명령어 중 "azure group deployment create ..." 는 "az group deployment create ..." 로 수정이 필요할 듯 합니다. 검토 부탁 드립니다.  

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 85d6ece8-6be3-7770-1740-7a9977246af0
* Version Independent ID: 623f3f5b-5acc-990b-3f04-c2017323c69b
* Content: [템플릿을 사용하여 Azure Service Bus 네임스페이스 항목 만들기](https://docs.microsoft.com/ko-kr/azure/service-bus-messaging/service-bus-resource-manager-namespace-topic)
* Content Source: [articles/service-bus-messaging/service-bus-resource-manager-namespace-topic.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/service-bus-messaging/service-bus-resource-manager-namespace-topic.md)
* Service: **service-bus-messaging**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49898](https://github.com/MicrosoftDocs/azure-docs/issues/49898) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/49898에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
