### ISSUE TITLE
yaml파일을 배포하는데 오류나여

### ISSUE THREAD

**Issue by Mr-Lee-oss** [MicrosoftDocs/azure-docs.ko-kr#1108]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6115d555-45a1-6539-4af6-fbc20a99f008
* Version Independent ID: 21f80c83-ba10-9b7e-c54f-51a9c140517c
* Content: [빠른 시작: Azure Kubernetes Service 클러스터 배포 - Azure Kubernetes Service](https://docs.microsoft.com/ko-kr/azure/aks/kubernetes-walkthrough)
* Content Source: [articles/aks/kubernetes-walkthrough.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/aks/kubernetes-walkthrough.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @Mr-Lee-oss
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요. @Mr-Lee-oss  님,
댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?
감사합니다.
Microsoft DOCS International 팀

**Comment by WooSung-Jung** [comment]
오류내역과 스크린샷을 첨부 가능할까요?

**Comment by CeciAc** [comment]
네, 맞아요/네, 맞습니다.

**Comment by CeciAc** [comment]
Hello, @Mr-Lee-oss 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
