### ISSUE TITLE
Translation errors in korean

### ISSUE THREAD

**Issue by captain9521** [MicrosoftDocs/azure-docs.ko-kr#1133]
Hi.
I found some translation errors at this page.
When i saw this page in korean to get information about moving resources like sshpublickeys, LabServices, it showed Yes, Yes.
However i translated in English, it displayed No, No.
Please check the below images.

Thanks.

![image](https://user-images.githubusercontent.com/38275650/97411897-32760d00-1944-11eb-94cf-27a21d2d28d2.png)

![image](https://user-images.githubusercontent.com/38275650/97411933-3b66de80-1944-11eb-9073-556cc9601bd9.png)

![image](https://user-images.githubusercontent.com/38275650/97411810-1a05f280-1944-11eb-8e8c-dfbc4d789d21.png)

![image](https://user-images.githubusercontent.com/38275650/97411860-28540e80-1944-11eb-90d0-fcddef53bdf5.png)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 23df5354-6833-a5da-0eb3-d860150c8b78
* Version Independent ID: 682ec206-0fda-3e0b-5841-543860a87e34
* Content: [리소스 종류별 이동 작업 지원 - Azure Resource Manager](https://docs.microsoft.com/ko-kr/azure/azure-resource-manager/management/move-support-resources)
* Content Source: [articles/azure-resource-manager/management/move-support-resources.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/azure-resource-manager/management/move-support-resources.md)
* Service: **azure-resource-manager**
* Sub-service: **management**
* GitHub Login: @tfitzmac
* Microsoft Alias: **tomfitz**

**Comment by WooSung-Jung** [comment]
I agree this issue. Please you should Pull request this issue of file. If you can't this. You write comment to request me. Best regard.

**Comment by WooSung-Jung** [comment]
This issue not updated recent. I will update Pull request soon.

**Comment by captain9521** [comment]
> This issue not updated recent. I will update Pull request soon.

Sorry for late reply. I check it now.
I made a Pull request.

**Comment by WooSung-Jung** [comment]
Should you close this issue.

**Comment by WooSung-Jung** [comment]
@captain9521 

https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1151
