### ISSUE TITLE
Invalid command

### ISSUE THREAD

**Issue by Taehun** [MicrosoftDocs/azure-docs.ko-kr#1141]
[여기에 피드백 입력]
```
ssh -i ~/.ssh/id_rsa.pub azureuser@10.111.12.123
````
To
```
ssh -i ~/.ssh/id_rsa azureuser@10.111.12.123
```
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 33cf041a-95dd-6332-52bf-6a71d3767bb8
* Version Independent ID: 96efc8cf-53e0-8a1c-fcf2-122f1b50b152
* Content: [SSH 키를 사용 하 여 Linux Vm에 연결 - Azure Virtual Machines](https://docs.microsoft.com/ko-kr/azure/virtual-machines/linux/ssh-from-windows)
* Content Source: [articles/virtual-machines/linux/ssh-from-windows.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/virtual-machines/linux/ssh-from-windows.md)
* Service: **virtual-machines**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by WooSung-Jung** [comment]
This repository is use for translation in Azure docs.
You should go origin documentation

> https://github.com/MicrosoftDocs/azure-docs

**Comment by WooSung-Jung** [comment]
Should you please close this issue?
