### ISSUE TITLE
한글에서 linkedTemplate.js 오타 linkedTemplate.json 

### ISSUE THREAD

**Issue by wcc8088** [MicrosoftDocs/azure-docs.ko-kr#1142]
[여기에 피드백 입력]

한글에서 linkedTemplate.js 오타 linkedTemplate.json 으로 바꿔주세요.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 78acfe06-c626-fd75-d3a4-13f7149ca40a
* Version Independent ID: 4d04da8a-df33-50ec-080b-8f983e38ecff
* Content: [연결 된 템플릿을 사용 하 여 템플릿 사양 만들기 - Azure Resource Manager](https://docs.microsoft.com/ko-kr/azure/azure-resource-manager/templates/template-specs-create-linked?tabs=azure-cli#feedback)
* Content Source: [articles/azure-resource-manager/templates/template-specs-create-linked.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/azure-resource-manager/templates/template-specs-create-linked.md)
* Service: **azure-resource-manager**
* Sub-service: **templates**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by WooSung-Jung** [comment]
해당 요청사항에 대해서 Pull Requests를 제가 올리도록 하겠습니다.

**Comment by WooSung-Jung** [comment]
해당 이슈에 대해 Pull Requests를 요청하였습니다.

> https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1143

**Comment by WooSung-Jung** [comment]
Pull Requests를 등록하였으나 확인에 시간이 걸리는 것 같습니다. 조금만 더 기달려주시면 감사하겠습니다.

**Comment by WooSung-Jung** [comment]
@wcc8088

해당 이슈 사항은 반영이 되었습니다. 이슈를 닫아주시면 감사하겠습니다.

> https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1143

**Comment by wcc8088** [comment]
수고하셨습니다.
