### ISSUE TITLE
some sentences are too long and the translation lost its original meaning

### ISSUE THREAD

**Issue by shenhuiying2017** [MicrosoftDocs/azure-docs.ko-kr#115]
1. Changed the behavior to only store a partial connection string with the key replaced by a token for Cloud Services diagnostics storage connection string.
Current translation: 이 동작은 키가 Cloud Services 진단 저장소 연결 문자열에 대한 토큰으로 교체되어 부분 연결 문자열만 저장하는 방식으로 변경되었습니다.
Suggestion translation:  Cloud Services 진단 저장소 연결 문자열 토큰 방식을 통해 부분 연결 문자열만 저장하도록 변경되었습니다.

2. Visual Studio Online team enhanced the Azure Cloud Services deployment task template so users could specify the storage key for setting diagnostics extension when publishing to Azure in Continuous Integration and Deployment. 
Current translation: Visual Studio Online 팀은 사용자가 연속 통합 및 배포에서 Azure에 게시할 때 진단 확장을 설정하기 위한 저장소 키를 지정할 수 있도록 Azure Cloud Services 배포 작업 템플릿을 개선했습니다.
Suggestion translation: Visual Studio Online 팀은 사용자가 연속 통합 및 배포단계에서 진단 확장에 필요한 저장키를 따로 선택하여 Azure에 게시할 수 있도록Azure Cloud Services 배포 작업 템플릿을 개선했습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5a036d54-3a6c-dcdb-49b4-130f2b2a5f84
* Version Independent ID: 68ddfbc2-5ee4-670e-87bc-f98484290088
* Content: [Azure SDK for .NET 2.9 릴리스 정보](https://docs.microsoft.com/ko-kr/azure/app-service/azure-sdk-dotnet-release-notes-2-9)
* Content Source: [articles/app-service/azure-sdk-dotnet-release-notes-2-9.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/app-service/azure-sdk-dotnet-release-notes-2-9.md)
* Service: **app-service**
* GitHub Login: @ChrisSfanos
* Microsoft Alias: **juliako**

**Comment by CeciAc** [comment]
Hi @shenhuiying2017,
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @shenhuiying2017 ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [Azure SDK for .NET 2.9 릴리스 정보](https://docs.microsoft.com/ko-kr/azure/app-service/azure-sdk-dotnet-release-notes-2-9).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
