### ISSUE TITLE
영문과 한국어판 문서 내용 상이

### ISSUE THREAD

**Issue by nsheo** [MicrosoftDocs/azure-docs.ko-kr#1158]
전용풀과 서버리스풀과의 비교 항목을 확인 중 영문판과 한국어판의 문서 내용이 다릅니다.
임시테이블 / 트리거 등 많은 항목이 내용이 다릅니다.
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 7183d46a-a815-a4ee-ed9d-273dffb14f41
* Version Independent ID: a1613e7c-f4f2-a61f-812e-9e11c3b91120
* Content: [Synapse SQL의 T-SQL 기능 차이점 - Azure Synapse Analytics](https://docs.microsoft.com/ko-kr/azure/synapse-analytics/sql/overview-features)
* Content Source: [articles/synapse-analytics/sql/overview-features.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/synapse-analytics/sql/overview-features.md)
* Service: **synapse-analytics**
* Sub-service: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by Arc-Jung** [comment]
@nsheo 
영문판과 비교 후 다른 점이 발견 되면 수정 후 Pull Request를 요청하겠습니다.

**Comment by Arc-Jung** [comment]
@nsheo 
![image](https://user-images.githubusercontent.com/43470915/113100857-ed2d7280-9236-11eb-8f92-77913955fae5.png)
언급해주신 문서의 번역의 오번역이 확인되었습니다. 이 문서를 제가 직접 수정하여 Pull Request를 요청하겠습니다.

**Comment by Arc-Jung** [comment]
@nsheo 
https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1160
Pull Request를 요청하였습니다. 확인해주시면 감사하겠습니다.

**Comment by nsheo** [comment]
@Arc-Jung 
네 해당 branch에서 내용 확인했습니다. 빠른대응 감사합니다.
다만 아직 웹문서상에는 반영되지않은것 같아보이는데 반영되는 시기를 알 수 있을까요?

**Comment by Arc-Jung** [comment]
@nsheo
레포지토리의 관리자가 보통 1~2 주에 한번 정도 PR을 병합합니다.
조금 여유를 가지고 기다려주시면 감사하겠습니다.
