### ISSUE TITLE
Apache Mahout 이 사용 가능한 Azure HDInsight 의 버전을 명시해 주세요

### ISSUE THREAD

**Issue by youngick** [MicrosoftDocs/azure-docs.ko-kr#1159]
[여기에 피드백 입력]

제가 알기로는 HDInsight 3.6에서는 Mahout 을 사용 가능하지만,

HDInsight 4.0에서는 Mahout 을 사용할 수  없습니다.

따라서 Apache Mahout 이 사용 가능한 Azure HDInsight 의 버전을 표시하는게 바람직해 보입니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: aa2185f8-2f8d-25c2-d1ce-19105871e907
* Version Independent ID: 9488462f-f53a-3834-c8d9-1be1d6fa985e
* Content: [Apache Mahout 및 Azure HDInsight를 사용하여 추천 생성](https://docs.microsoft.com/ko-kr/azure/hdinsight/hadoop/apache-hadoop-mahout-linux-mac)
* Content Source: [articles/hdinsight/hadoop/apache-hadoop-mahout-linux-mac.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/hdinsight/hadoop/apache-hadoop-mahout-linux-mac.md)
* Service: **hdinsight**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment]
Translation:
As far as I know, you can use Mahout in HDInsight 3.6,
Mahout is not available in HDInsight 4.0.
So it seems desirable for Apache Mahout to show the version of Azure HDInsight available.

Response: we can add a note in the doc. Thanks for mentioning this!

**Comment by JasonWHowell** [comment]
#please-close
