### ISSUE TITLE
Translation and really.

### ISSUE THREAD

**Issue by hynazomba** [MicrosoftDocs/azure-docs.ko-kr#207]
이 번역은 Azure를 이용하여 실험데이터를 저장하는 법과 순서를 기술한것인지  어떤 실험 혹은 project를 위한 응용 프로그램 개발인지  번역에 확실히 나타나지 않는 것 같네요. 각종기능이 무엇을 하는데 쓰이는지  주어를  생략하면 우리글에서는 내용파악이 어려울 것 같아요. 엄청난 개발을 한 것은 인정합니다  .  건투를 빕니다.  박수를 보냅니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 3f31ca49-7462-b30f-2c28-e3955f1ea753
* Version Independent ID: 54e1c15c-fb8e-7c88-2a3f-314397600dde
* Content: [Azure Machine Learning 서비스(미리 보기)용 모델 자습서 작성](https://docs.microsoft.com/ko-kr/azure/machine-learning/desktop-workbench/tutorial-classifying-iris-part-2)
* Content Source: [articles/machine-learning/desktop-workbench/tutorial-classifying-iris-part-2.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/machine-learning/desktop-workbench/tutorial-classifying-iris-part-2.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by DavidPrio** [comment]
Hello, @hynazomba ,
 
Thank you for your feedback. We need more information to be able to deal with this issue. Can you please provide more detailed instructions and specific lines that need revision/fixing?

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
안녕하세요. , @hynazomba , 

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요. , @hynazomba ,

피드백을 주셔서 감사합니다.

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다.

감사합니다.
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요. , @hynazomba ,

피드백을 주셔서 감사합니다.

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다.

감사합니다.
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @hynazomba 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/machine-learning/desktop-workbench/tutorial-classifying-iris-part-2 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
