### ISSUE TITLE
Databricks serverless 옵션은

### ISSUE THREAD

**Issue by sklim2002** [MicrosoftDocs/azure-docs.ko-kr#209]
현재 번역이 "Databricks 서버를 사용하지 않음"이라고 되어 있는데 "Databricks 서버리스" 라고 표기하면 좋겠습니다. 옵션 중 하나이기 때문입니다

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2eea9046-9156-2096-d59b-afbe816c7390
* Version Independent ID: 7e667e9f-08f9-94fa-add5-346db61837ca
* Content: [Azure Databricks란?](https://docs.microsoft.com/ko-kr/azure/azure-databricks/what-is-azure-databricks)
* Content Source: [articles/azure-databricks/what-is-azure-databricks.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/azure-databricks/what-is-azure-databricks.md)
* Service: **azure-databricks**
* GitHub Login: @nitinme
* Microsoft Alias: **nitinme**

**Comment by LisandroSu** [comment]
안녕하세요. @sklim2002 

의견을 보내 주셔서 감사합니다. 이 문제를 해결하려면 더 많은 정보가 필요합니다. 수정 / 수정이 필요한 자세한 지침과 특정 라인을 제공해주십시오.
 
친절하고,
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. @sklim2002 

귀하의 의견에 다시 한번 감사드립니다.
죄송 합니다만, 우리는 여전히 정보가 누락되어 귀하의 의견을 처리 할 수 없습니다. 현재이 GitHub 문제를 종결하고 있지만 앞으로 더 많은 의견을 제출하시기 바랍니다.

친절하고,
Microsoft DOCS 국제 팀
