### ISSUE TITLE
Can not Start 'iotedge' service

### ISSUE THREAD

**Issue by hwantkim** [MicrosoftDocs/azure-docs.ko-kr#210]
Start-Service : Failed to start service 'iotedge (iotedge)'.
At line:1 char:1
+ Start-Service iotedge
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController)
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 64575e7c-664c-4d6b-a440-24c91e93def5
* Version Independent ID: 17d9481c-a75b-bbfd-1f9a-76fc3d6b2930
* Content: [Azure IoT Edge + Windows 빠른 시작](https://docs.microsoft.com/ko-kr/azure/iot-edge/quickstart#install-and-start-the-iot-edge-runtime)
* Content Source: [articles/iot-edge/quickstart.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/iot-edge/quickstart.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by LisandroSu** [comment]
Hello, @hwantkim , 
  
Thank you for your feedback. 
  
Can you provide us more info regarding your issue?
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @hwantkim 

Thanks for the answer. 

We are actively reviewing your comments and will get back to you soon.

**Comment by LisandroSu** [comment]
Hello, @hwantkim 

The file is in being translated to all languages now. The file will be updated soon. I will be closing the issue.

Kind regards,
Microsoft DOCS International Team
