### ISSUE TITLE
링크 깨짐

### ISSUE THREAD

**Issue by seokju-na** [MicrosoftDocs/azure-docs.ko-kr#211]
<img width="700" alt="2018-08-09 2 26 14" src="https://user-images.githubusercontent.com/13250888/43879750-5f843de6-9be0-11e8-812d-422612e6f7c1.png">

본문의 2번째 줄에 "JSON 스키마는 http://json.schemastore.org/host에 있습니다."에서 링크로 연결된 사이트가 "http://json.schemastore.org/host에"로 지정되어 있습니다. 뒤에 '에'자를 제거하여 "http://json.schemastore.org/host"로 링크 변경이 필요합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 27150c55-615f-fb44-d5e4-7b5815631c7d
* Version Independent ID: 271006dc-afce-99f3-0790-41fa2e35b22b
* Content: [Azure Functions에 대한 host.json 참조](https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-host-json)
* Content Source: [articles/azure-functions/functions-host-json.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/azure-functions/functions-host-json.md)
* Service: **functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by LisandroSu** [comment]
안녕하세요. , @seokju-na , 

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요, @seokju-na 님.  

피드백을 주셔서 감사합니다. 
 
당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 [Azure Functions에 대한 host.json 참조](https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-host-json)에 게시했습니다.  

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 

감사합니다. 
Microsoft DOCS 국제 팀
