### ISSUE TITLE
QuickTest 코드는 없나요?

### ISSUE THREAD

**Issue by insung3511** [MicrosoftDocs/azure-docs.ko-kr#212]
이미 customvision.ai에서 공부도 시키고 태그도 다 해놓았는데요, 테스트 결과 값을 코드로 짜서 쓰고 싶은데 혹시 예제 코드 없나요?? 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b9957cb6-3fc1-b7ae-db20-f90b6a833faf
* Version Independent ID: 90421a02-0e49-5bf4-3cd1-f94c80031b3a
* Content: [Python 및 Custom Vision API를 사용한 데이터 검색 - Azure Cognitive Service](https://docs.microsoft.com/ko-kr/azure/cognitive-services/custom-vision-service/python-tutorial-od)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/python-tutorial-od.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/cognitive-services/Custom-Vision-Service/python-tutorial-od.md)
* Service: **cognitive-services**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by LisandroSu** [comment]
안녕하세요, @insung3511 님. 

귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 

DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 

설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  

감사합니다. 
Microsoft DOCS 국제 팀
