### ISSUE TITLE
Error in Translate

### ISSUE THREAD

**Issue by ho426-lee** [MicrosoftDocs/azure-docs.ko-kr#213]
In Korean document, ko-KR is in supported language for STT
In English document, there is no ko-KR in table.
Korean version document has error.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 4de08d1f-8114-7bef-7ef4-022f79c69742
* Version Independent ID: 4c0ceab9-24ed-de01-db30-31acf1de0f48
* Content: [Speech Service 지원되는 언어 - Microsoft Cognitive Services - Microsoft Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/Speech-Service/supported-languages)
* Content Source: [articles/cognitive-services/Speech-Service/supported-languages.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/cognitive-services/Speech-Service/supported-languages.md)
* Service: **cognitive-services**
* GitHub Login: @v-jerkin
* Microsoft Alias: **v-jerkin**

**Comment by LisandroSu** [comment]
Hello, @ho426-lee 

Thank you for your feedback.

The English file was updated recently. The new korean version is being localized and will be updated shortly.

Regards,
Microsoft DOCS International Team.

**Comment by LisandroSu** [comment]
Hello, @ho426-lee ,

Thank you for your feedback and suggestion. 
 
The English source file has been updated recently. Your feedback will be considered when localizing the new version.

Many thanks for your contribution.

Kind regards, 
Microsoft C&E Localization Team
