### ISSUE TITLE
Change Feed를 정밀하게 사용하기에는 설명이 너무 부족하다.

### ISSUE THREAD

**Issue by wayne-kim** [MicrosoftDocs/azure-docs.ko-kr#214]
모든 피드를 받는 건 쉽게 합니다. 하지만 특정 파티션에 대해서 피드만 받으려고하니까. 방법을 찾을 수 없습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: fdcc897a-d6df-3305-e9cb-01889a3c5d4f
* Version Independent ID: 739a9fc7-3782-a860-ac6d-4194fd1ce2e8
* Content: [Azure Cosmos DB에서 변경 피드 지원 사용](https://docs.microsoft.com/ko-kr/azure/cosmos-db/change-feed)
* Content Source: [articles/cosmos-db/change-feed.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/cosmos-db/change-feed.md)
* Service: **cosmos-db**
* GitHub Login: @rafats
* Microsoft Alias: **rafats**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13242](https://github.com/MicrosoftDocs/azure-docs/issues/13242) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
안녕하세요, @wayne-kim 님.

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은   원본 설명서와 관련되어 있습니다.
 
따라서 이 문제를 영어 리포지토리에 마이그레이션하고   있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/13242 에서 문제 상태를 확인하세요.
 
당사 문서에 대한 귀하의 기여에 진심으로 감사   드립니다.

감사합니다.
Microsoft DOCS 국제 팀
