### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#215]
실습을 따라하려고해도 각종 종속정 문제 및 버전차이로 인해 원할히 진행이 어렵네요..
자마린 폼즈를 통한 빠른시작으로 만든 최초 앱을 열고난뒤 맨처음 설치하는 누겟패키지부터 오류가 나옵니다

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6f503e37-b16e-c92c-8668-313428451053
* Version Independent ID: edc66d3e-bf88-3c4d-a148-6288a7022f16
* Content: [Xamarin.Forms 앱에 푸시 알림 추가](https://docs.microsoft.com/ko-kr/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push)
* Content Source: [articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push.md)
* Service: **app-service-mobile**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13808](https://github.com/MicrosoftDocs/azure-docs/issues/13808) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
안녕하세요, @yourera님.

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은   원본 설명서와 관련되어 있습니다.
 
따라서 이 문제를 영어 리포지토리에 마이그레이션하고   있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/13808에서 문제 상태를 확인하세요.

당사 문서에 대한 귀하의 기여에 진심으로 감사   드립니다.

감사합니다.
Microsoft DOCS 국제 팀
