### ISSUE TITLE
please update doc

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#216]
실습을 따라하려고해도 각종 종속정 문제 및 버전차이로 인해 원할히 진행이 어렵네요..
자마린 폼즈를 통한 빠른시작으로 만든 최초 앱을 열고난뒤 맨처음 설치하는 누겟패키지부터 오류가 나옵니다

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6f503e37-b16e-c92c-8668-313428451053
* Version Independent ID: edc66d3e-bf88-3c4d-a148-6288a7022f16
* Content: [Xamarin.Forms 앱에 푸시 알림 추가](https://docs.microsoft.com/ko-kr/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push)
* Content Source: [articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push.md)
* Service: **app-service-mobile**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by LisandroSu** [comment]
안녕하세요. @yourera 
 
귀하의 기부에 많은 감사드립니다. Google 팀에서 사용자의 의견을 검토 한 결과이 문제가 이미 기록 된 것 같습니다.
문제 # https://github.com/MicrosoftDocs/azure-docs.ko-kr/issues/215 을 검토하십시오. 이러한 이유로 우리는 중복되어 있기 때문에이 문제를 종결 짓고 있습니다.
 
친절하고,
Microsoft DOCS 국제 팀
