### ISSUE TITLE
mistranslation

### ISSUE THREAD

**Issue by options** [MicrosoftDocs/azure-docs.ko-kr#219]
-'서버를 사용하지 않는 비교'는 의미가 와닿지 않습니다. "서버리스 비교", "serverless 비교" 정도가 적당한 대역이 될것 같습니다.
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 82ee9751-961d-7109-63d6-813b1862c632
* Version Independent ID: 583d1b2f-9c1a-3580-9d14-37bb551eaf44
* Content: [Flow, Logic Apps, Functions 및 WebJobs 비교 - Azure](https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs)
* Content Source: [articles/azure-functions/functions-compare-logic-apps-ms-flow-webjobs.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/azure-functions/functions-compare-logic-apps-ms-flow-webjobs.md)
* Service: **functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by LisandroSu** [comment]
안녕하세요. , @options 

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요, @options 님.  

 피드백을 주셔서 감사합니다. 

 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 [Flow, Logic Apps, Functions 및 WebJobs 비교 - Azure](https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs)에 게시했습니다.  

 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 

 감사합니다. 
Microsoft DOCS 국제 팀
