### ISSUE TITLE
Impossible to submit the issue has title in korean

### ISSUE THREAD

**Issue by options** [MicrosoftDocs/azure-docs.ko-kr#220]
I couldn't submit feedback if the title was written in Korean language though Korean page.

**Comment by LisandroSu** [comment]
Hello, @options ,
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @options 

We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @options 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
