### ISSUE TITLE
Apple Developer 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#225]
단순히 테스트를 위한 준비를 하고있는데 애플 개발자 맴버 등록을 하려면 1년에 12만원을 지불해야합니다. 해당 실습을 진행하기위해서는 애플 계정만있어도 되는지 아니면 꼭 개발자맴버
까지가 필요한지 질문드립니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 45afd17d-e909-ccd9-01c3-f746bdf406a2
* Version Independent ID: d2c8cc69-5a37-4c73-d48b-9c058cf4595e
* Content: [Azure Notification Hubs를 사용하여 Xamarin.iOS 앱에 알림 푸시](https://docs.microsoft.com/ko-kr/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started)
* Content Source: [articles/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started.md)
* Service: **notification-hubs**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by LisandroSu** [comment]
안녕하세요, @yourera 님. 

 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 

 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 

 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  

 감사합니다.
Microsoft DOCS 국제 팀

**Comment by yourera** [comment]
해당 설명서대로 실습을 진행하고있습니다.
하지만 인증서를 Azure에 올리게 될때 Failed to validate credentials with APNS. Error is The credentials supplied to the package were not recognized 다음의 오류가 발생합니다.

이부분에 있어서 설명서에서 구체적으로 .p12 파일을 만드는 법을 가이드 해주셔야할 것 같습니다.
