### ISSUE TITLE
Is Apple Developer Members Essential?

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#226]
If you are just preparing for testing, you will have to pay $ 120 per year to register for an Apple Developer Member. You need to have an Apple account or a Developer
I will ask you whether you need to.

Is it for app store registration?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 45afd17d-e909-ccd9-01c3-f746bdf406a2
* Version Independent ID: d2c8cc69-5a37-4c73-d48b-9c058cf4595e
* Content: [Azure Notification Hubs를 사용하여 Xamarin.iOS 앱에 알림 푸시](https://docs.microsoft.com/ko-kr/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started)
* Content Source: [articles/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started.md)
* Service: **notification-hubs**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by LisandroSu** [comment]
안녕하세요, @<참가자의 GITHUB 이름>님. 

 귀하의 기여에 매우 감사 드립니다. 당사의 팀에서 귀하의 피드백을 검토한 결과 이 문제는 이미 기록된 것으로 나타났습니다. 

 문제 #[226](https://github.com/MicrosoftDocs/azure-docs.ko-kr/issues/226)를 확인하세요. 이 문제는 중복되기 때문에 종료하겠습니다. 

 감사합니다. 
Microsoft DOCS 국제 팀
