### ISSUE TITLE
Backup tool 이 잘못 기재되어 있습니다.

### ISSUE THREAD

**Issue by ashurei** [MicrosoftDocs/azure-docs.ko-kr#261]
비즈니스 연속성 &gt; 개요 페이지에서 MySQL 에는 pg_dump, PostgreSQL 에는 mysqldump 로 기재되어 있네요. 서로 뒤바뀐 것으로 보입니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0eb2cae6-197f-94b4-53ba-12f99dff5a4e
* Version Independent ID: 259006d1-760e-b2fa-d0bb-6e952b951e3a
* Content: [Azure Database for PostgreSQL의 비즈니스 연속성 개요](https://docs.microsoft.com/ko-kr/azure/postgresql/concepts-business-continuity)
* Content Source: [articles/postgresql/concepts-business-continuity.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/postgresql/concepts-business-continuity.md)
* Service: **postgresql**
* GitHub Login: @rachel-msft
* Microsoft Alias: **raagyema**

**Comment by CeciAc** [comment]
안녕하세요. , @ashurei , 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by rachel-msft** [comment]
Thank you for pointing out the error. I will submit a fix in the original English docs. They should be available in the Korean docs soon.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #20889](https://github.com/MicrosoftDocs/azure-docs/issues/20889) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
안녕하세요, @ashurei 님. 
 귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다. 
 따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/20889에서 문제 상태를 확인하세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다. 
Microsoft DOCS 국제 팀
