### ISSUE TITLE
Jenkins 구성관련

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#311]
Jenkins 구성섹션에서 ssh로 VM 접속 후 다음 명령을 내리는 과정에서 추가 진행이 안됩니다.
sudo cat /var/lib/jenkins/secrets/initialAdminPassword

zerobig@zero-VM:~$ sudo cat /var/lib/jenkins/secrets/initialAdminPassword
cat: /var/lib/jenkins/secrets/initialAdminPassword: No such file or directory

반복적으로 시도해봤고 기다렸다가 해당 명령을 수행해봐도 동일한 결과이며
해당 VM에는 도커, 젠킨스 설치에 관한 아무런 로그 이력도 남아있지 않음을 확인했습니다.

무엇이 잘못된것인지 확인 및 해결 부탁 드립니다.
이 랩에서 너무 많은 시간을 반복해서 소모하고 있습니다.

감사합니다.
 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a230cf42-66c2-e0d1-983a-7b920251fe2c
* Version Independent ID: 6d17ff45-c7fd-2715-382e-14905760b594
* Content: [자습서 - Azure에서 Jenkins를 사용하여 개발 파이프라인 만들기](https://docs.microsoft.com/ko-kr/azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd#feedback)
* Content Source: [articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md)
* Service: **virtual-machines-linux**
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by LisandroSu** [comment]
안녕하세요, @zer0big 님. 

 귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다. 
 따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - XXX에서 문제 상태를 확인하세요. 

 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24193](https://github.com/MicrosoftDocs/azure-docs/issues/24193) via [**ZenHub**](https://www.zenhub.com/)
