### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by MyeongJaeKim** [MicrosoftDocs/azure-docs.ko-kr#312]
모듈 간 통신을 용이하게 하는  IoT Edge 허브를 메시지 broker로 사용하면 모듈이 서로 독립적으로 유지됩니다.
--&gt;
IoT Edge 허브는 모듈 간 통신을 용이하게 합니다.  IoT Edge 허브를 메시지 broker로 사용하면 모듈이 서로 독립적으로 유지됩니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: c424cd61-2f44-8a10-bce8-5a18fb1279f3
* Version Independent ID: 62824def-6ec5-0b0e-d909-88f82c647cb8
* Content: [런타임에서 디바이스를 관리하는 방법 알아보기 - Azure IoT Edge](https://docs.microsoft.com/ko-kr/azure/iot-edge/iot-edge-runtime)
* Content Source: [articles/iot-edge/iot-edge-runtime.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/iot-edge/iot-edge-runtime.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
안녕하세요. , @MyeongJaeKim 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @MyeongJaeKim

소중한 의견을 공유해 주셔서 감사드립니다.

Microsoft Azure 현지화 팀은 사용자의 편의를 위한 한국어 콘텐츠를 제공하기 위해 최선을 다하고 있습니다. 

제안해 주신 업데이트 내용을 검토한 결과, 이번 제안 건은 사용자 개인의 선호도에 따른 업데이트 요청으로 기존의 번역 내용에 기술적/문법적인 문제가 없는 것으로 판단되어 즉각적인 업데이트는 진행하지 않는 것으로 결정되었습니다. 

다만, 향후 현지화 작업 진행에 있어 제안해 주신 내용을 참고 및 반영할 수 있도록 노력하겠습니다. 

향후 추가 제안 사항이 있으시다면 언제든지 공유해 주시기 바랍니다. 

감사합니다.
