### ISSUE TITLE
Koran Translation

### ISSUE THREAD

**Issue by MyeongJaeKim** [MicrosoftDocs/azure-docs.ko-kr#313]
메시지 라우팅을 사용하면 원격 분석 데이터를 IoT 디바이스에서 기본 제공된 Event Hub 호환 엔드포인트 또는 Blob Storage, Service Bus 큐, Service Bus 토픽 및 Event Hubs와 같은 사용자 지정 엔드포인트에 전송할 수 있습니다.
--&gt;
메시지 라우팅을 사용하면 IoT 디바이스의 분석용 데이터를 기본 제공된 Event Hub 호환 엔드포인트 또는 Blob Storage, Service Bus 큐, Service Bus 토픽 및 Event Hubs와 같은 사용자 지정 엔드포인트에 전송할 수 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: f233412c-4242-e9a6-e09d-c5b07775dd00
* Version Independent ID: 3a940d2c-77bb-b8ff-8864-9fc6ef16c122
* Content: [Azure IoT Hub(.NET)로 메시지 라우팅 구성](https://docs.microsoft.com/ko-kr/azure/iot-hub/tutorial-routing)
* Content Source: [articles/iot-hub/tutorial-routing.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/iot-hub/tutorial-routing.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by CeciAc** [comment]
안녕하세요. , @MyeongJaeKim  
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by robinsh** [comment]
I had to put this in bing translate to understand. Is there a question here? I don't agree with the rewording of the sentence in question, at least not after it's converted to English. Is that what the issue is?

**Comment by CeciAc** [comment]
Hi @robinsh 
Please, disregard this thread, we are reviewing this with our KOR linguist,
We'll get back to you if we need anything from your side

Kind regards, 
Microsoft DOCS International Team

**Comment by robinsh** [comment]
@CeciAc Okay, thanks for letting me know. It's just a rewording of that sentence, and makes it less clear, not more clear. LMK if you need anything from me.

**Comment by CeciAc** [comment]
안녕하세요. , @MyeongJaeKim

소중한 의견을 공유해 주셔서 감사드립니다.

Microsoft Azure 현지화 팀은 사용자의 편의를 위한 한국어 콘텐츠를 제공하기 위해 최선을 다하고 있습니다.

제안해 주신 업데이트 내용을 검토한 결과, 이번 제안 건은 사용자 개인의 선호도에 따른 업데이트 요청으로 기존의 번역 내용에 기술적/문법적인 문제가 없는 것으로 판단되어 즉각적인 업데이트는 진행하지 않는 것으로 결정되었습니다.

다만, 향후 현지화 작업 진행에 있어 제안해 주신 내용을 참고 및 반영할 수 있도록 노력하겠습니다. 
향후 추가 제안 사항이 있으시다면 언제든지 공유해 주시기 바랍니다. 

감사합니다.
