### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by MyeongJaeKim** [MicrosoftDocs/azure-docs.ko-kr#314]
이 변형에도 불구하고 IoT Hub 디바이스 관리는 기능, 패턴 및 코드 라이브러리를 다양한 디바이스 및 최종 사용자에게 제공합니다.
--&gt;
이 다양성에도 불구하고 IoT Hub 디바이스 관리는 기능, 패턴 및 코드 라이브러리를 다양한 디바이스 및 최종 사용자에게 제공합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9e966591-00c1-5578-2e96-b72e4a90f1f6
* Version Independent ID: afdf80d0-d8ba-86ad-b61c-d0d64c7ea890
* Content: [Azure IoT Hub 디바이스 관리 개요](https://docs.microsoft.com/ko-kr/azure/iot-hub/iot-hub-device-management-overview)
* Content Source: [articles/iot-hub/iot-hub-device-management-overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/iot-hub/iot-hub-device-management-overview.md)
* Service: **iot-hub**
* GitHub Login: @bzurcher
* Microsoft Alias: **briz**

**Comment by CeciAc** [comment]
안녕하세요. , @MyeongJaeKim 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @MyeongJaeKim 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/iot-hub/iot-hub-device-management-overview에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
