### ISSUE TITLE
"건축" is wrong title of section.

### ISSUE THREAD

**Issue by steelflea** [MicrosoftDocs/azure-docs.ko-kr#318]
영어 원문을 잘 못 한글화 시킨 것으로 "아키텍처"라는 제목으로 바꿔주세요.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 627bf595-d3a1-bbdd-b045-b6c4a580fdb3
* Version Independent ID: 529fbe9a-c711-c1a0-5697-5853b1e51071
* Content: [Azure의 Desired State Configuration 개요](https://docs.microsoft.com/ko-kr/azure/virtual-machines/extensions/dsc-overview)
* Content Source: [articles/virtual-machines/extensions/dsc-overview.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/virtual-machines/extensions/dsc-overview.md)
* Service: **virtual-machines-windows**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by CeciAc** [comment]
안녕하세요. , @
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @steelflea 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/virtual-machines/extensions/dsc-overview 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
