### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by insankim** [MicrosoftDocs/azure-docs.ko-kr#320]
VM은 중지/할당 취소할 필요가 없으며 
이 부분은 원문에 대한 번역이 잘못 되었습니다. 

원문: The VM does need to be stopped\deallocated, 
올바른번역: VM은 반드시 중지/할당 취소가 되어야 합니다.

중요한 부분이므로 빠른 수정이 필요할 것 같습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 12ea7e90-b545-258a-3bc8-dd840e1c0835
* Version Independent ID: 26e1a7b0-5762-5a37-6263-d8563ad66640
* Content: [PowerShell을 통해 Azure VM에 대한 OS 디스크 교체](https://docs.microsoft.com/ko-kr/azure/virtual-machines/windows/os-disk-swap)
* Content Source: [articles/virtual-machines/windows/os-disk-swap.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/virtual-machines/windows/os-disk-swap.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
안녕하세요. , @insankim 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @insankim 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/virtual-machines/windows/os-disk-swap 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀

**Comment by insankim** [comment]
Hello Cecilia,
​
Thank you for notifying the update.
I believe this change can reduce confusion for our customers!
​
Appreciate for promptly taking the action.
​
Kind regards,
Insan.kim@microsoft.com 
​
-----Original Message-----
