### ISSUE TITLE
샘플 앱 GitHub 링크 깨짐

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#322]
샘플 앱을 얻기 위한 링크(https://github.com/azooinmyluggage/fabrikam-node)가 404로 처리됩니다.
조치 부탁 드립니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 043a153e-a24d-0230-b3ee-aa9969865dd5
* Version Independent ID: 89a5fe17-668e-de7b-7720-60fa98112ba0
* Content: [자습서 - Azure DevOps Services를 사용하여 Jenkins에서 Azure VM으로 CI/CD](https://docs.microsoft.com/ko-kr/azure/virtual-machines/linux/tutorial-build-deploy-jenkins)
* Content Source: [articles/virtual-machines/linux/tutorial-build-deploy-jenkins.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/virtual-machines/linux/tutorial-build-deploy-jenkins.md)
* Service: **devops**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25683](https://github.com/MicrosoftDocs/azure-docs/issues/25683) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
안녕하세요, @zer0big 님. 
 귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다. 
 따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/25683에서 문제 상태를 확인하세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다. 
Microsoft DOCS 국제 팀
