### ISSUE TITLE
it can not get json data from search news api

### ISSUE THREAD

**Issue by dalsw** [MicrosoftDocs/azure-docs.ko-kr#329]
[여기에 피드백 입력]

    static String host = "https://api.cognitive.microsoft.com";
    static String path = "/bing/v7.0/news/search";

    static String searchTerm = "Microsoft";

    public static SearchResults SearchNews (String searchQuery) throws Exception {
        // construct URL of search request (endpoint + query string)
        URL url = new URL(host + path + "?q=" +  URLEncoder.encode(searchQuery, "UTF-8"));
        HttpsURLConnection connection = (HttpsURLConnection)url.openConnection();
        connection.setRequestProperty("Ocp-Apim-Subscription-Key", subscriptionKey);

        Log.i("test bing","SearchResults: " + url);

        // receive JSON body
        InputStream stream = connection.getInputStream();

        String response = new Scanner(stream).useDelimiter("\\A").next();

        Log.i("test bing","SearchResults: " + response); 

---------------------------------------------------------------
I insert valid api key but it returns "null" value. what's wrong?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9a3e3ff9-4094-409b-af1c-9f8c7f7931f2
* Version Independent ID: 632651c7-ca16-7c96-0133-a1faea506823
* Content: [빠른 시작: C#을 사용하여 웹 검색 수행 - Bing Web Search REST API](https://docs.microsoft.com/ko-kr/azure/cognitive-services/bing-news-search/java#feedback)
* Content Source: [articles/cognitive-services/Bing-News-Search/java.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/cognitive-services/Bing-News-Search/java.md)
* Service: **cognitive-services**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by CeciAc** [comment]
Hello, @dalsw 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
