### ISSUE TITLE
Cluster Upgrade Error

### ISSUE THREAD

**Issue by zer0big** [MicrosoftDocs/azure-docs.ko-kr#340]
[root@zerovm azure-voting-app-redis]# az aks get-upgrades --resource-group zeroResourceGroup --name zeroAKSCluster --output table
Name     ResourceGroup      MasterVersion    NodePoolVersion    Upgrades
-------  -----------------  ---------------  -----------------  --------------
default  zeroResourceGroup  1.11.9           1.11.9             1.12.6, 1.12.7
[root@zerovm azure-voting-app-redis]# az aks upgrade --resource-group zeroResourceGroup --name zeroAKSCluster --kubernetes-version 1.12.6
super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 251, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 267, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 35, in load_arguments
    super().load_arguments(command)
TypeError: super() takes at least 1 argument (0 given)

--&gt;  포털에서는 정상적으로 업그레이드 됨

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a14a3f84-28b4-0a2a-4da7-47cb4d66689f
* Version Independent ID: d1ffdd88-ab9a-9f55-8689-526e7415b326
* Content: [Azure의 Kubernetes 자습서 - 클러스터 업그레이드](https://docs.microsoft.com/ko-kr/azure/aks/tutorial-kubernetes-upgrade-cluster#feedback)
* Content Source: [articles/aks/tutorial-kubernetes-upgrade-cluster.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/aks/tutorial-kubernetes-upgrade-cluster.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
안녕하세요, @zer0big  님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀
