### ISSUE TITLE
Dataflow

### ISSUE THREAD

**Issue by jenyang2** [MicrosoftDocs/azure-docs.ko-kr#470]
How do I change from dataframe to dataflow?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 65ca3600-cbad-b9eb-3c7e-22b5251226ec
* Version Independent ID: 8881b6f3-c64d-f758-15c8-79e10e9764a9
* Content: [회귀 모델 자습서: 데이터 준비 - Azure Machine Learning service](https://docs.microsoft.com/ko-kr/azure/machine-learning/service/tutorial-data-prep#feedback)
* Content Source: [articles/machine-learning/service/tutorial-data-prep.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/machine-learning/service/tutorial-data-prep.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sihhu
* Microsoft Alias: **MayMSFT**

**Comment by CeciAc** [comment]
Hello, @jenyang2

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
