### ISSUE TITLE
How can I contribute to example powershell code?

### ISSUE THREAD

**Issue by wafe** [MicrosoftDocs/azure-docs.ko-kr#55]
There is a bug in create-vm-from-snapshot.ps1 . How can I edit it?

The link is below:
`!code-powershell[main](../../../powershell_scripts/virtual-machine/create-vm-from-snapshot/create-vm-from-snapshot.ps1 "Create VM from managed os disk")`

**Comment by SunnyDeng** [comment]
@wafe thank you for the contribution. Could you please indicate the bug? 
I am cc the writer @ramankumarlive

**Comment by wafe** [comment]
@SunnyDeng 
Wow, thank you for your response.
There is code using not defined $storageType variable.

**Comment by SunnyDeng** [comment]
Ping @ramankumarlive

**Comment by ramankumarlive** [comment]
@wafe please go ahead and raise a pull request with the changes. We will validate and merge the pull request.

**Comment by SunnyDeng** [comment]
@wafe please do as @ramankumarlive said. I close the ISSUE here.

**Comment by wafe** [comment]
@SunnyDeng oh, sorry for late response. @ramankumarlive i don’t know where the ps1 files are. please tell me repository address.
