### ISSUE TITLE
프로젝트 소음 이라는 번역이 다소 어색합니다.

### ISSUE THREAD

**Issue by toad0475** [MicrosoftDocs/azure-docs.ko-kr#740]
프로젝트 소음을 "프로젝트 어쿠스틱" 또는 "프로젝트 Acoustics"로 하는것이 현재보다 덜 어색합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 899e500b-5671-8d07-d60e-e65b2ecf7f03
* Version Independent ID: 2be53ee4-fad8-21c3-d908-73c9bd674d64
* Content: [음향 시뮬레이션을 사용한 디자인 개념](https://docs.microsoft.com/ko-kr/azure/cognitive-services/acoustics/design-process#feedback)
* Content Source: [articles/cognitive-services/Acoustics/design-process.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/cognitive-services/Acoustics/design-process.md)
* Service: **cognitive-services**
* Sub-service: **acoustics**
* GitHub Login: @kegodin
* Microsoft Alias: **kegodin**

**Comment by CeciAc** [comment]
안녕하세요. , @toad0475
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. , @toad0475
피드백을 주셔서 감사합니다. 문제의 페이지가 기계 번역되어 항상 완벽하게 이해할 수 있는 것은 아닙니다. 최근에 오른쪽에 "영어로 읽기" 옵션이 추가되어 언어 설정을 변경하지 않고도 영어 버전으로 전환할 수 있습니다. 
감사합니다.
Microsoft DOCS 국제 팀
