### ISSUE TITLE
myVmPublic에서 저장소 계정에 대해 엑세스가 됩니다.

### ISSUE THREAD

**Issue by HoyeonHan** [MicrosoftDocs/azure-docs.ko-kr#881]
예제대로 스토리지 계정의 방화벽 및 가상 네트워크 메뉴에서 private 서브넷에 대해서만 엔드포인트를 설정해도 public 서브넷에 연결된 myVmPublic에서 스토리지에 접근이 됩니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: cfd9533e-c174-cd48-0f72-a58457efa958
* Version Independent ID: b7a77b77-61c2-5e89-cb4b-0b9a502fce71
* Content: [PaaS 리소스에 대한 네트워크 액세스 제한 - 자습서 - Azure Portal](https://docs.microsoft.com/ko-kr/azure/virtual-network/tutorial-restrict-network-access-to-resources#feedback)
* Content Source: [articles/virtual-network/tutorial-restrict-network-access-to-resources.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/virtual-network/tutorial-restrict-network-access-to-resources.md)
* Service: **virtual-network**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34775](https://github.com/MicrosoftDocs/azure-docs/issues/34775) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
안녕하세요, @HoyeonHan 님. 

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다. 

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/azure-docs/issues/34775 에서 문제 상태를 확인하세요. 

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  

감사합니다. 
Microsoft DOCS 국제 팀
