### ISSUE TITLE
please fix the Dependency problem. 

### ISSUE THREAD

**Issue by lab021rnd** [MicrosoftDocs/azure-docs.ko-kr#91]
please fix the Dependency problem.  newsoft.json, other azure sdk...
azure sdk team needs to talk about this

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6e88ea08-81ef-2b5a-b9d6-539e85592672
* Version Independent ID: f2d8b7b4-906a-d1f5-5201-fc22a7890955
* Content: [Visual Studio를 사용하여 Azure에서 첫 번째 함수 만들기](https://docs.microsoft.com/ko-kr/azure/azure-functions/functions-create-your-first-function-visual-studio)
* Content Source: [articles/azure-functions/functions-create-your-first-function-visual-studio.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/azure-functions/functions-create-your-first-function-visual-studio.md)
* Service: **functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by v-maudel** [comment]
Hello, @lab021rnd ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @lab021rnd , 
  
Thank you for your feedback. We need more information to be able to deal with this issue. Can you please provide more detailed instructions and specific lines that need revision/fixing? 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @lab021rnd,
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @lab021rnd
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
