### ISSUE TITLE
페이지 제목 '분선' -> '분산' 

### ISSUE THREAD

**Issue by mnrvacho** [MicrosoftDocs/azure-docs.ko-kr#911]
변경 부탁드립니다 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e47329a5-4087-9c3b-1561-3223916a10b1
* Version Independent ID: b2d8689b-c5f9-baa5-45d2-363ed3728310
* Content: [Azure Database for PostgreSQL – 하이퍼스케일(Citus)(미리 보기)에서 분산된 데이터](https://docs.microsoft.com/ko-kr/azure/postgresql/concepts-hyperscale-distributed-data#feedback)
* Content Source: [articles/postgresql/concepts-hyperscale-distributed-data.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/postgresql/concepts-hyperscale-distributed-data.md)
* Service: **postgresql**
* Sub-service: **hyperscale-citus**
* GitHub Login: @jonels-msft
* Microsoft Alias: **jonels**

**Comment by srvbpigh** [comment]
Hello, @mnrvacho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @mnrvacho님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/postgresql/concepts-hyperscale-distributed-data#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
