### ISSUE TITLE
HA or DR options for Azure Data Explorer

### ISSUE THREAD

**Issue by JihongL** [MicrosoftDocs/azure-docs.ko-kr#916]
Is there any  HA or DR options  for ADX?
I couldn't find any on MS docs.

**Comment by srvbpigh** [comment]
Hello, @JihongL
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JihongL

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
