### ISSUE TITLE
HA or DR options for Azure Data Explorer

### ISSUE THREAD

**Issue by JihongL** [MicrosoftDocs/azure-docs.ko-kr#917]
Hi.
Is there any HA or DR options for ADX?
I couldn't find any on MS docs.
If region that I deployed ADX be unable, or some problems happen on ADX itself, How can I handle it?  

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a338c71f-e871-3618-7125-1ca4f27b9ae4
* Version Independent ID: 4b5c847c-1630-6d7c-fe26-fc90982451d3
* Content: [Azure 데이터 탐색기 클러스터의 상태 확인](https://docs.microsoft.com/ko-kr/azure/data-explorer/check-cluster-health)
* Content Source: [articles/data-explorer/check-cluster-health.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/data-explorer/check-cluster-health.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by srvbpigh** [comment]
Hello, @JihongL
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JihongL

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by JihongL** [comment]
@srvbpigh @CeciAc 

I leave question with "feedback directly on Github" button by bottom of Docs. 
And is not product feedback, is question about functions of ADX.
I hope I can get useful answers.

Regards,
Jihong.

**Comment by orspod** [comment]
@JihongL when creating a cluster in ADX, use the [new "availability zones" capability](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-portal#create-a-cluster). This protects your applications and data from datacenter failures. [More info on availability zones](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview). Note that availability zones is only available in specific regions.
