### ISSUE TITLE
please update xamarin ver

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#962]
this doc update date is 2019.6.5

However, there are still instructions for registering in Android Studio, not in xamarin Forms with Visual Studio . 
I just copied the Firebase basics document.

For those who are new to Jamarin, this trivial problem comes with difficulty.****

**Comment by srvbpigh** [comment]
Hello, @yourera
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yourera** [comment]
Hello,@CeciAc

I am studying mobile application development for the first time with Xamarin.
Using Azure Docs to study Xamarin to Push notification.

However, the documentation often reveals different versions.

For example, in this case, while looking at the push description in Google Firebase,

The content and capture of the document is based on Android Studio, not Visual Studio.
 
If you look at the data, there are other well-guided parts

I know a lot of documents have been added this time. 
The Xamarin document has been watched recently, so the updates are very encouraging.

But The documentation was added and it seemed a bit unorganized, so there was some confusion in practice.

Thank you

**Comment by CeciAc** [comment]
Hello, @yourera

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
